version: '3.7'
services:
  sonar_server:
    image: sonarqube:community
    depends_on:
      - database
    container_name: sonar_server
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://database:5432/sonar
      - SONARQUBE_JDBC_USERNAME=${SONAR_USER}
      - SONARQUBE_JDBC_PASSWORD=${SONAR_PASSWORD}
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions

  database:
    image: postgres:alpine
    container_name: postgres_server
    environment:
      - POSTGRES_USER=${SONAR_USER}
      - POSTGRES_PASSWORD=${SONAR_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonar_conf:
    name: sonar_conf
  sonar_data:
    name: sonar_data
  sonar_extensions:
    name: sonar_extensions
  postgresql:
    name: postgresql
  postgresql_data:
    name: postgresql_data
    